"""remove location column for now

Revision ID: becc62359526
Revises: 005d1b239d3b
Create Date: 2024-09-30 18:52:12.055754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'becc62359526'
down_revision: Union[str, None] = '005d1b239d3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('location', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
