"""update db for first time with alembic

Revision ID: cbfc63b8b8a8
Revises: 
Create Date: 2024-09-30 18:04:12.942373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cbfc63b8b8a8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('hostname', sa.String(length=255), nullable=True))
    op.add_column('events', sa.Column('startDateTime', sa.DateTime(), nullable=True))
    op.add_column('events', sa.Column('endDateTime', sa.DateTime(), nullable=True))
    op.add_column('events', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('events', sa.Column('isShareable', sa.Boolean(), nullable=True))
    op.add_column('events', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('events', sa.Column('allowQA', sa.Boolean(), nullable=True))
    op.add_column('events', sa.Column('phone', sa.String(length=15), nullable=True))
    op.add_column('events', sa.Column('slug', sa.String(length=255), nullable=False))
    op.alter_column('events', 'description',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.create_index(op.f('ix_events_description'), 'events', ['description'], unique=False)
    op.create_index(op.f('ix_events_slug'), 'events', ['slug'], unique=True)
    op.drop_column('events', 'datetime')
    op.drop_column('events', 'is_public')
    op.drop_column('events', 'location_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('location_name', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('events', sa.Column('is_public', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('datetime', mysql.DATETIME(), nullable=True))
    op.drop_index(op.f('ix_events_slug'), table_name='events')
    op.drop_index(op.f('ix_events_description'), table_name='events')
    op.alter_column('events', 'description',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=1000),
               existing_nullable=True)
    op.drop_column('events', 'slug')
    op.drop_column('events', 'phone')
    op.drop_column('events', 'allowQA')
    op.drop_column('events', 'email')
    op.drop_column('events', 'owner_id')
    op.drop_column('events', 'isShareable')
    op.drop_column('events', 'location')
    op.drop_column('events', 'endDateTime')
    op.drop_column('events', 'startDateTime')
    op.drop_column('events', 'hostname')
    # ### end Alembic commands ###
