"""adjusted question table

Revision ID: 136ba8fb96f8
Revises: b673c37852b3
Create Date: 2025-02-02 12:44:22.273542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '136ba8fb96f8'
down_revision: Union[str, None] = 'b673c37852b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'updated_at')
    op.add_column('questions', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'created_at')
    op.add_column('events', sa.Column('updated_at', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
