"""increase state column length

Revision ID: 489c5320424b
Revises: 6cccb6683ea8
Create Date: 2024-12-03 18:21:07.463063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '489c5320424b'
down_revision: Union[str, None] = '6cccb6683ea8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('locations', 'state',
               existing_type=mysql.VARCHAR(length=2),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('placeID', mysql.VARCHAR(length=255), nullable=True))
    op.alter_column('locations', 'state',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=2),
               existing_nullable=False)
    op.drop_column('locations', 'placeId')
    op.add_column('events', sa.Column('hostname', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('events', 'hostName')
    # ### end Alembic commands ###
