"""Sync database schema

Revision ID: b31c9568d211
Revises: 489c5320424b
Create Date: 2024-12-09 19:22:11.357084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b31c9568d211'
down_revision: Union[str, None] = '489c5320424b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('hostName', sa.String(length=255), nullable=True))
    op.drop_column('events', 'hostname')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('hostname', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('events', 'hostName')
    # ### end Alembic commands ###
