"""add full_address to locations table

Revision ID: d79c771420e9
Revises: aa4673ff4c40
Create Date: 2025-02-01 15:28:20.185150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd79c771420e9'
down_revision: Union[str, None] = 'aa4673ff4c40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('full_address', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'full_address')
    # ### end Alembic commands ###
